name: Cifar10
data_dir: #Path to your Dataset
save_path: #Path to save the backbone
filepath: #Path to save weights
K: 1
knn_k: 200
crop_max: 1
image_size: 32
batch_size: 1024
num_workers: 32
num_classes: 10
drop_last: False
mean: [0.491, 0.482, 0.447]
std: [0.247, 0.243, 0.262]
