name: Cifar100
data_dir: #Path to your Dataset
save_path: #Path to save the backbone
filepath: #Path to save weights
K: 1
crop_max: 1
knn_k: 200
image_size: 32
batch_size: 1024
num_workers: 32
num_classes: 100
drop_last: False
    
mean: [0.5071, 0.4867, 0.4408] 
std: [0.2675, 0.2565, 0.2761]
