name: Imagenet
data_dir: /home/gen/yash/OurData/data/imagenet/ILSVRC/
save_path: /home/gen/yash/work/Result_zip/LT-Results
filepath: results/MeanWeights

K: 1
image_size: 224
crop_max: 1
batch_size: 128
num_workers: 32
num_classes: 1000
drop_last: False

mean: [0.485,0.456,0.406]
std: [0.229,0.224,0.225]
