name: Imagenet
data_dir: #Path to your Dataset
save_path: #Path to save the backbone
filepath: #Path to save weights
K: 1
image_size: 224
crop_max: 1
batch_size: 128
num_workers: 32
num_classes: 1000
drop_last: False

mean: [0.485,0.456,0.406]
std: [0.229,0.224,0.225]
