name: Stl10
data_dir: #Path to your Dataset
save_path: #Path to save the backbone
filepath: #Path to save weights
K: 1
image_size: 96
crop_max: 1
batch_size: 256
num_workers: 32
num_classes: 10
drop_last: False

mean: [0.485,0.456,0.406]
std: [0.485,0.456,0.406]

