name: TinyImagenet
data_dir: #Path to your Dataset
save_path: #Path to save the backbone
filepath: #Path to save weights

data_list: #Path for datafile wnids.txt
val_list: #Path for data file out.txt

K: 1
crop_max: 1
image_size: 64
batch_size: 256
num_workers: 32
num_classes: 200
drop_last: False

mean: [0.485,0.456,0.406]
std: [0.229,0.224,0.225]
